export const projectCategories = [
  {
    accent: 'violet',
    description:
      'Client and personal web builds — from government registration platforms and violator tracking systems to AI-powered apps and themed landing experiences.',
    id: 'web-projects',
    platform: 'Web Applications',
    role: 'Front-End Developer',
    roles: ['UI/UX Designer', 'Front-End Developer', 'Full-Stack Developer'],
    shortName: 'Web Projects',
    tabLabel: 'Web',
    status: 'Live',
    subtitle: 'Websites & Web Applications',
    title: 'WEB PROJECTS',
    type: 'web',
  },
  {
    accent: 'blue',
    description:
      'Mobile apps for e-commerce, quizzes, government systems, and job matching — built with React Native and Flutter for real-world field and consumer use.',
    id: 'mobile-projects',
    platform: 'Mobile Applications',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'React JS Developer'],
    shortName: 'Mobile Projects',
    tabLabel: 'Mobile',
    status: 'Live',
    subtitle: 'iOS & Android Experiences',
    title: 'MOBILE PROJECTS',
    type: 'mobile',
  },
  {
    accent: 'amber',
    description:
      'CMS-powered funnels and corporate sites on Go High Level and WordPress — course sales, recruitment, IT staffing, and partner landing pages.',
    id: 'cms-projects',
    platform: 'CMS Websites',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'CMS Builder'],
    shortName: 'CMS Projects',
    tabLabel: 'CMS',
    status: 'Live',
    subtitle: 'WordPress & Go High Level',
    title: 'CMS PROJECTS',
    type: 'cms',
  },
  {
    accent: 'rose',
    description:
      'Figma UI/UX for mobile and web products — dashboards, registration flows, rewards platforms, e-commerce concepts, and design systems.',
    id: 'figma-projects',
    platform: 'Figma & UI/UX',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer', 'Product Designer'],
    shortName: 'Figma Projects',
    tabLabel: 'UI/UX',
    status: 'Live',
    subtitle: 'UI/UX Design & Prototyping',
    title: 'FIGMA PROJECTS',
    type: 'figma',
  },
]

export const portfolioProjects = [
  {
    categoryId: 'web-projects',
    description:
      'Web-based tricycle permit registration platform for local government use. Operators register digitally through the web portal, receive QR codes for verification, get SMS notifications, and admins manage registrations through dashboards.',
    features: ['Permit registration', 'QR verification', 'SMS notifications', 'Admin dashboards', 'Receipt verification'],
    id: 'trireg-web',
    liveUrl: null,
    platform: 'Web',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['React', 'Vite', 'Figma', 'QR Code System'],
    timeline: 'May 2025 – October 2025',
    title: 'TriReg Web',
  },
  {
    categoryId: 'web-projects',
    description:
      'Violator tracking system for PNP and LGU Cabagan. Authorities track violators, issue citations, compute fines automatically, and send SMS alerts with real-time visualization.',
    features: ['Violator tracking', 'Role-based dashboards', 'Citation tools', 'SMS alerts', 'Automated fines'],
    id: 'vtrack-web-mobile',
    liveUrl: null,
    platform: 'Web',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['Flutter', 'Dart', 'React', 'Vite', 'Figma', 'Real-time Data'],
    timeline: 'May 2025 – October 2025',
    title: 'VTrack Web & Mobile',
  },
  {
    categoryId: 'web-projects',
    description:
      'AI-powered virtual veterinarian platform using OpenAI GPT-3.5. Users ask pet health questions and receive AI-generated veterinary guidance through a web chat interface.',
    features: ['AI pet care advice', 'Virtual vet chatbot', 'REST API backend', 'Vercel deployment'],
    id: 'doctor-santi',
    liveUrl: 'https://santi-doc-cy6n.vercel.app/',
    platform: 'Web',
    projectType: 'Personal Project',
    role: 'Full-Stack Developer',
    roles: ['Full-Stack Developer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'ChatGPT API'],
    timeline: 'July 2025 – Present',
    title: 'Doctor Santi',
  },
  {
    categoryId: 'web-projects',
    description:
      'Platform helping homeowners find reliable design, renovation, and construction firms through intelligent matching instead of manual contractor searching.',
    features: ['Homeowner matching', 'Landing funnel', 'Responsive design', 'UI/UX in Figma'],
    id: 'network-homeowners',
    liveUrl: 'https://landing-funnel-iota.vercel.app/',
    platform: 'Web',
    projectType: 'Personal Project',
    role: 'Full-Stack Developer',
    roles: ['UI/UX Designer', 'Front-End Developer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['React', 'Figma', 'UI/UX Design'],
    timeline: '2024 – Present',
    title: 'Network Homeowners',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Mobile e-commerce app for a pottery business with product browsing and checkout via Cash on Delivery or GCash, optimized for mobile shoppers.',
    features: ['Product listings', 'COD & GCash payments', 'Mobile checkout', 'Shopping cart'],
    id: 'marians-pottery',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance (Part-Time)',
    role: 'React JS Developer',
    roles: ['React JS Developer'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['React Native', 'Expo Router', 'E-commerce'],
    timeline: 'August 2024 – October 2024',
    title: "Marian's Pottery",
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Interactive mobile quiz application with multiple question types and real-time score tracking, designed to be engaging across devices.',
    features: ['Multiple question types', 'Score tracking', 'Responsive mobile UI', 'Engaging UX'],
    id: 'quiz-whirl-app',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['React Native', 'Quiz Application'],
    timeline: 'August 2024 – October 2024',
    title: 'Quiz Whirl App',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Mobile companion to TriReg — operators register permits, receive QR codes and SMS notifications, with admin mobile access to tracking dashboards.',
    features: ['Mobile registration', 'QR codes', 'SMS notifications', 'Admin dashboards'],
    id: 'trireg-mobile-app',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['Flutter', 'Dart', 'Figma', 'QR Code System'],
    timeline: 'May 2025 – October 2025',
    title: 'TriReg Mobile App',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Mobile violator tracking for LGU field use — role-based dashboards, citation tools, and SMS alerts with real-time data updates.',
    features: ['Field tracking', 'Role-based dashboards', 'Citation tools', 'SMS alerts'],
    id: 'vtrack-mobile-app',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['Flutter', 'Dart', 'Figma', 'Real-time Data'],
    timeline: 'May 2025 – October 2025',
    title: 'VTrack Mobile App',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Job-matching app for primary-collar workers connecting employers and workers with role-based dashboards for admins, clients, and workers.',
    features: ['Job matching', 'Role-based dashboards', 'Ratings & notifications', 'Admin management'],
    id: 'laborlinkz',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Personal / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'UI/UX Designer'],
    status: 'Concept',
    team: 'Solo Project',
    technologies: ['React Native', 'Figma', 'UI/UX Design'],
    timeline: 'November 2023 – January 2024',
    title: 'LaborLinkz',
  },
  {
    categoryId: 'figma-projects',
    description: 'Mobile UI/UX for VTrack violator tracking — modern interface and seamless navigation crafted in Figma.',
    features: ['Mobile UX', 'Violator tracking flows', 'Modern interface'],
    id: 'vtrack-uiux-mobile',
    liveUrl:
      'https://www.figma.com/design/BBSDb1xjDozdEwui2vIAeb/VTRACK-Mobile?node-id=0-1&p=f&t=JuBJWG9TxUcwUFMD-0',
    platform: 'Mobile',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: '2024 – 2025',
    title: 'Vtrack UI/UX Design (Mobile)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Mobile UI/UX for TriReg permit registration — clean layouts and intuitive flows for operators and admins.',
    features: ['Registration flows', 'Clean mobile layouts', 'Admin screens'],
    id: 'trireg-uiux-mobile',
    liveUrl:
      'https://www.figma.com/design/mO2Y5WmASDZNNuvSbEYtqs/TRIREG-NEW-MOBILE-APP?node-id=360-7&t=9EbKOhq0bAGZVN7q-0',
    platform: 'Mobile',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: '2024 – 2025',
    title: 'TriReg UI/UX Design (Mobile)',
  },
  {
    categoryId: 'figma-projects',
    description: 'LaborLinkz mobile UI/UX prioritizing accessibility and engaging journeys for job seekers and employers.',
    features: ['Accessibility', 'Job matching UI', 'Worker & client flows'],
    id: 'laborlinkz-uiux-mobile',
    liveUrl: 'https://www.figma.com/design/rlsh7gKzyxvC7Kw1xdloK2/Laborlinkz?t=JuBJWG9TxUcwUFMD-0',
    platform: 'Mobile',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Mobile UI/UX', 'Accessibility'],
    timeline: '2023 – 2024',
    title: 'LaborLinkz UI/UX Design (Mobile)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Web dashboard UI/UX for VTrack — usability-focused design for government and admin users.',
    features: ['Web dashboards', 'Admin usability', 'Modern web interface'],
    id: 'vtrack-uiux-web',
    liveUrl:
      'https://www.figma.com/design/dNLjZlmTlTWOGJd4wpdK8I/VTRACK-Web-Prototype?node-id=0-1&p=f&t=JuBJWG9TxUcwUFMD-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: '2024 – 2025',
    title: 'Vtrack UI/UX Design (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Web UI/UX for TriReg — registration and admin workflow screens with clean navigation in Figma.',
    features: ['Registration workflows', 'Admin dashboard design', 'Web layouts'],
    id: 'trireg-uiux-web',
    liveUrl: 'https://www.figma.com/design/tukviOiiuBGE4KOeuECMnI/TRIREG-NEW?t=9EbKOhq0bAGZVN7q-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: '2024 – 2025',
    title: 'TriReg UI/UX Design (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Professional workflow UI/UX for the Pro Assisting web application — intuitive navigation for business users.',
    features: ['Professional workflows', 'Business UX', 'Web app screens'],
    id: 'pro-assisting-uiux',
    liveUrl: 'https://www.figma.com/design/gSL72RPA5UYsFqi2iAAsHA/Pro-Assisting?t=9EbKOhq0bAGZVN7q-0',
    platform: 'Web',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: '2024',
    title: 'Pro Assisting UI/UX Design (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Brioray web app UI/UX with modern aesthetics and a user-friendly browsing experience in Figma.',
    features: ['Modern aesthetics', 'Product-focused design', 'Web interface'],
    id: 'brioray-uiux-web',
    liveUrl:
      'https://www.figma.com/design/XVSqvw546Y7wON3PymZokB/Brioray?node-id=0-1&p=f&t=k9X840YzjxDVaPFx-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: '2024 – 2025',
    title: 'Brioray UI/UX Design (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Australian Rewards Club web platform UI/UX — rewards and membership flows with modern visuals.',
    features: ['Rewards platform', 'Membership flows', 'Modern visuals'],
    id: 'arc-uiux-web',
    liveUrl:
      'https://www.figma.com/design/yMTyPxE0fDEwOBf3qAqPNP/ARC-WEB?node-id=0-1&p=f&t=Ko3FbWaPHcuRAI0D-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: '2024',
    title: 'ARC - Australian Rewards Club (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Mobile-first rewards app UI for Australian Rewards Club — intuitive navigation and seamless experience.',
    features: ['Mobile-first design', 'Rewards navigation', 'Seamless UX'],
    id: 'arc-uiux-mobile',
    liveUrl:
      'https://www.figma.com/design/bNtCVbo3LXVZaoCEl3RtmV/WEB-APP-VIEW-OF-AUSTRALIAN-REWARDS-CLUB?node-id=66-6&t=fpFBPiDTn72vxUEY-0',
    platform: 'Mobile',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: '2024',
    title: 'Australian Rewards Club Mobile UI',
  },
  {
    categoryId: 'figma-projects',
    description: 'Plant care and community app UI — track, monitor, and care for plants with a calming, simple interface.',
    features: ['Plant tracking', 'Community features', 'Calming UI'],
    id: 'plantpal-uiux',
    liveUrl:
      'https://www.figma.com/design/7A48SiV6ks8z2NKc1BOOMO/UI-UX-PROJECt?node-id=27-6&t=mFMb4oHeInEtkZdP-0',
    platform: 'Mobile',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: '2024',
    title: 'PlantPal UI/UX Design',
  },
  {
    categoryId: 'figma-projects',
    description: 'Analytics toolkit UI for Amazon sellers — profitability, eligibility, and sales potential dashboards.',
    features: ['Data visualization', 'Seller analytics', 'Dashboard design'],
    id: 'sourcing-analysis-uiux',
    liveUrl:
      'https://www.figma.com/design/p3DY30bs9Nt9f1ZCMKK97q/Sourcing-Analysis-Simplified?node-id=0-1&p=f&t=bKcLMHFOUD0GSrRN-0',
    platform: 'Web',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Web UI/UX', 'Data Visualization'],
    timeline: '2024',
    title: 'Sourcing Analysis Simplified',
  },
  {
    categoryId: 'figma-projects',
    description: 'Plant e-commerce app UI — discover, learn about, and purchase houseplants for home and office.',
    features: ['Plant e-commerce', 'Discovery & browsing', 'Shopping flows'],
    id: 'planto-uiux',
    liveUrl: 'https://www.figma.com/design/FhdXWVWA6blrVGY4r6k4AC/Planto?node-id=0-1&p=f&t=ZXxaDVWDVcUh0o4A-0',
    platform: 'Mobile',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Mobile UI/UX', 'E-commerce'],
    timeline: '2024',
    title: 'Planto',
  },
  {
    categoryId: 'figma-projects',
    description:
      'UI/UX for Network Homeowners — landing funnel and homeowner matching flows designed in Figma.',
    features: ['Homeowner matching', 'Landing funnel', 'Responsive layouts'],
    id: 'network-homeowners-uiux',
    liveUrl:
      'https://www.figma.com/design/Ml48WHNOP5jd8iP4PJBcb3/Untitled?node-id=0-1&p=f&t=5kgm0lhNTGbNuA5V-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: '2024 – Present',
    title: 'Network Homeowners',
  },
  {
    categoryId: 'cms-projects',
    description:
      'High-converting course sales funnel for professional LED installation training — ABCDE framework, 48 video modules, testimonials, and FAQ.',
    features: ['Course funnel', '48 video modules', 'Testimonials', 'Lead capture'],
    id: 'ultimate-led-course',
    liveUrl: 'https://app.gohighlevel.com/v2/preview/D0RHH7qtq1TPIQeWRhlm?notrack=true',
    platform: 'Go High Level',
    projectType: 'CMS Project',
    role: 'CMS Builder',
    roles: ['CMS Builder', 'Front-End Developer'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['Go High Level', 'Landing Pages', 'Lead Capture'],
    timeline: '2024 – 2025',
    title: 'Ultimate LED Course',
  },
  {
    categoryId: 'cms-projects',
    description:
      'Corporate WordPress site for an IT staffing firm with 23+ years of experience — services, careers, testimonials, and contact flows.',
    features: ['Corporate services', 'Careers hub', 'Lead generation', 'Divi layouts'],
    id: 'vertere-global',
    liveUrl: 'https://vertere-gs.com/',
    platform: 'WordPress',
    projectType: 'CMS Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'CMS Builder'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['WordPress', 'Divi', 'PHP', 'HTML', 'CSS'],
    timeline: '2024 – 2025',
    title: 'Vértere Global Solutions',
  },
  {
    categoryId: 'cms-projects',
    description:
      'Recruitment agency website connecting employers and talent across the Philippines — placement, executive search, RPO, and careers hub.',
    features: ['Recruitment services', 'Industry pages', 'Careers hub', 'Testimonials'],
    id: 'a7-recruitment',
    liveUrl: 'https://a7recruitment.com/',
    platform: 'WordPress',
    projectType: 'CMS Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'CMS Builder'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['WordPress', 'Elementor', 'PHP', 'HTML', 'CSS'],
    timeline: '2024 – 2025',
    title: 'A7 Recruitment',
  },
  {
    categoryId: 'cms-projects',
    description:
      'Partner landing page for a plug-and-sell LED tape light kiosk system — product bundles, retail benefits, FAQ, and partner registration.',
    features: ['Product bundles', 'Partner registration', 'FAQ', 'Lead capture'],
    id: 'brioray-cms',
    liveUrl: 'https://sites.leadconnectorhq.com/preview/qBNYaLk0iHBBaPZomRvQ?notrack=true',
    platform: 'Go High Level',
    projectType: 'CMS Project',
    role: 'CMS Builder',
    roles: ['CMS Builder', 'Front-End Developer'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['Go High Level', 'Landing Pages', 'Lead Capture'],
    timeline: '2024 – 2025',
    title: 'Brioray',
  },
]

projectCategories.forEach((category) => {
  const items = portfolioProjects.filter((project) => project.categoryId === category.id)
  category.projects = items.map((project) => ({ id: project.id, title: project.title }))
  category.projectCount = items.length
})
