export const projectCategories = [
  {
    accent: 'violet',
    description:
      'Client and personal web builds — from government registration platforms and violator tracking systems to AI-powered apps and themed landing experiences.',
    id: 'web-projects',
    platform: 'Web Applications',
    role: 'Front-End Developer',
    roles: ['UI/UX Designer', 'Front-End Developer', 'Full-Stack Developer'],
    shortName: 'Web Projects',
    tabLabel: 'Web',
    status: 'Live',
    subtitle: 'Websites & Web Applications',
    title: 'WEB PROJECTS',
    type: 'web',
  },
  {
    accent: 'blue',
    description:
      'Mobile apps for e-commerce, quizzes, government systems, and job matching — built with React Native and Flutter for real-world field and consumer use.',
    id: 'mobile-projects',
    platform: 'Mobile Applications',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'React JS Developer'],
    shortName: 'Mobile Projects',
    tabLabel: 'Mobile',
    status: 'Live',
    subtitle: 'iOS & Android Experiences',
    title: 'MOBILE PROJECTS',
    type: 'mobile',
  },
  {
    accent: 'amber',
    description:
      'CMS-powered funnels and corporate sites on Go High Level and WordPress — course sales, recruitment, IT staffing, and partner landing pages.',
    id: 'cms-projects',
    platform: 'CMS Websites',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'CMS Builder'],
    shortName: 'CMS Projects',
    tabLabel: 'CMS',
    status: 'Live',
    subtitle: 'WordPress & Go High Level',
    title: 'CMS PROJECTS',
    type: 'cms',
  },
  {
    accent: 'rose',
    description:
      'Figma UI/UX for mobile and web products — dashboards, registration flows, rewards platforms, e-commerce concepts, and design systems.',
    id: 'figma-projects',
    platform: 'Figma & UI/UX',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer', 'Product Designer'],
    shortName: 'Figma Projects',
    tabLabel: 'UI/UX',
    status: 'Live',
    subtitle: 'UI/UX Design & Prototyping',
    title: 'FIGMA PROJECTS',
    type: 'figma',
  },
  {
    accent: 'green',
    description:
      'Professional video editing projects — promotional videos, social media content, and multimedia storytelling for clients and personal brands.',
    id: 'video-projects',
    platform: 'Video Production',
    role: 'Video Editor',
    roles: ['Video Editor', 'Content Creator'],
    shortName: 'Video Projects',
    tabLabel: 'Video',
    status: 'Live',
    subtitle: 'Video Editing & Multimedia',
    title: 'VIDEO PROJECTS',
    type: 'video',
  },
]

export const portfolioProjects = [
  {
    categoryId: 'web-projects',
    description:
      'Web-based tricycle permit registration platform for local government use. Operators register digitally through the web portal, receive QR codes for verification, get SMS notifications, and admins manage registrations through dashboards.',
    features: ['Permit registration', 'QR verification', 'SMS notifications', 'Admin dashboards', 'Receipt verification'],
    id: 'trireg-web',
    liveUrl: null,
    platform: 'Web',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['React', 'Vite', 'Figma', 'QR Code System'],
    timeline: 'May 2025 – October 2025',
    title: 'TriReg Web',
  },
  {
    categoryId: 'web-projects',
    description:
      'Violator tracking system for PNP and LGU Cabagan. Authorities track violators, issue citations, compute fines automatically, and send SMS alerts with real-time visualization.',
    features: ['Violator tracking', 'Role-based dashboards', 'Citation tools', 'SMS alerts', 'Automated fines'],
    id: 'vtrack-web-mobile',
    liveUrl: null,
    platform: 'Web',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['Flutter', 'Dart', 'React', 'Vite', 'Figma', 'Real-time Data'],
    timeline: 'May 2025 – October 2025',
    title: 'VTrack Web & Mobile',
  },
  {
    categoryId: 'web-projects',
    description:
      'AI-powered virtual veterinarian platform using OpenAI GPT-3.5. Users ask pet health questions and receive AI-generated veterinary guidance through a web chat interface.',
    features: ['AI pet care advice', 'Virtual vet chatbot', 'REST API backend', 'Vercel deployment'],
    id: 'doctor-santi',
    liveUrl: 'https://santi-doc-cy6n.vercel.app/',
    platform: 'Web',
    projectType: 'Personal Project',
    role: 'Full-Stack Developer',
    roles: ['Full-Stack Developer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'ChatGPT API'],
    timeline: 'July 2025',
    title: 'Doctor Santi',
  },
  {
    categoryId: 'web-projects',
    description:
      'CEST 2.0 dashboard for DOST Region II — centralized monitoring of regional science programs with sign-in flows, budget visualizations, project overview charts, and recent activity tracking.',
    features: ['Admin dashboards', 'Budget visualizations', 'Project overview', 'Guest access', 'Activity tracking'],
    id: 'cest-dashboard',
    liveUrl: null,
    platform: 'Web',
    projectType: 'Client Project',
    role: 'Web Developer',
    roles: ['Front-End Developer', 'UI/UX Designer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['React', 'JavaScript', 'HTML', 'CSS', 'Data Visualization'],
    timeline: 'April 2026 – June 2026',
    title: 'CEST Dashboard',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Mobile e-commerce app for a pottery business with product browsing and checkout via Cash on Delivery or GCash, optimized for mobile shoppers.',
    features: ['Product listings', 'COD & GCash payments', 'Mobile checkout', 'Shopping cart'],
    id: 'marians-pottery',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance (Part-Time)',
    role: 'React JS Developer',
    roles: ['React JS Developer'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['React Native', 'Expo Router', 'E-commerce'],
    timeline: 'August 2024 – October 2024',
    title: "Marian's Pottery",
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Interactive mobile quiz application with multiple question types and real-time score tracking, designed to be engaging across devices.',
    features: ['Multiple question types', 'Score tracking', 'Responsive mobile UI', 'Engaging UX'],
    id: 'quiz-whirl-app',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['React Native', 'Quiz Application'],
    timeline: 'August 2024 – October 2024',
    title: 'Quiz Whirl App',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Mobile companion to TriReg — operators register permits, receive QR codes and SMS notifications, with admin mobile access to tracking dashboards.',
    features: ['Mobile registration', 'QR codes', 'SMS notifications', 'Admin dashboards'],
    id: 'trireg-mobile-app',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['Flutter', 'Dart', 'Figma', 'QR Code System'],
    timeline: 'May 2025 – October 2025',
    title: 'TriReg Mobile App',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Mobile violator tracking for LGU field use — role-based dashboards, citation tools, and SMS alerts with real-time data updates.',
    features: ['Field tracking', 'Role-based dashboards', 'Citation tools', 'SMS alerts'],
    id: 'vtrack-mobile-app',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Client / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer'],
    status: 'Live',
    team: 'Team Project',
    technologies: ['Flutter', 'Dart', 'Figma', 'Real-time Data'],
    timeline: 'May 2025 – October 2025',
    title: 'VTrack Mobile App',
  },
  {
    categoryId: 'mobile-projects',
    description:
      'Job-matching app for primary-collar workers connecting employers and workers with role-based dashboards for admins, clients, and workers.',
    features: ['Job matching', 'Role-based dashboards', 'Ratings & notifications', 'Admin management'],
    id: 'laborlinkz',
    liveUrl: null,
    platform: 'Mobile',
    projectType: 'Personal / Freelance Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'UI/UX Designer'],
    status: 'Concept',
    team: 'Solo Project',
    technologies: ['React Native', 'Figma', 'UI/UX Design'],
    timeline: 'November 2023 – January 2024',
    title: 'LaborLinkz',
  },
  {
    categoryId: 'figma-projects',
    description: 'Mobile UI/UX for VTrack violator tracking — modern interface and seamless navigation crafted in Figma.',
    features: ['Mobile UX', 'Violator tracking flows', 'Modern interface'],
    id: 'vtrack-uiux-mobile',
    liveUrl:
      'https://www.figma.com/design/BBSDb1xjDozdEwui2vIAeb/VTRACK-Mobile?node-id=0-1&p=f&t=JuBJWG9TxUcwUFMD-0',
    platform: 'Mobile',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: 'May 2025 – October 2025',
    title: 'Vtrack UI/UX Design (Mobile)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Mobile UI/UX for TriReg permit registration — clean layouts and intuitive flows for operators and admins.',
    features: ['Registration flows', 'Clean mobile layouts', 'Admin screens'],
    id: 'trireg-uiux-mobile',
    liveUrl:
      'https://www.figma.com/design/mO2Y5WmASDZNNuvSbEYtqs/TRIREG-NEW-MOBILE-APP?node-id=360-7&t=9EbKOhq0bAGZVN7q-0',
    platform: 'Mobile',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: 'May 2025 – October 2025',
    title: 'TriReg UI/UX Design (Mobile)',
  },
  {
    categoryId: 'figma-projects',
    description: 'LaborLinkz mobile UI/UX prioritizing accessibility and engaging journeys for job seekers and employers.',
    features: ['Accessibility', 'Job matching UI', 'Worker & client flows'],
    id: 'laborlinkz-uiux-mobile',
    liveUrl: 'https://www.figma.com/design/rlsh7gKzyxvC7Kw1xdloK2/Laborlinkz?t=JuBJWG9TxUcwUFMD-0',
    platform: 'Mobile',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Mobile UI/UX', 'Accessibility'],
    timeline: 'November 2023 – January 2024',
    title: 'LaborLinkz UI/UX Design (Mobile)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Web dashboard UI/UX for VTrack — usability-focused design for government and admin users.',
    features: ['Web dashboards', 'Admin usability', 'Modern web interface'],
    id: 'vtrack-uiux-web',
    liveUrl:
      'https://www.figma.com/design/dNLjZlmTlTWOGJd4wpdK8I/VTRACK-Web-Prototype?node-id=0-1&p=f&t=JuBJWG9TxUcwUFMD-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: 'May 2025 – October 2025',
    title: 'Vtrack UI/UX Design (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Web UI/UX for TriReg — registration and admin workflow screens with clean navigation in Figma.',
    features: ['Registration workflows', 'Admin dashboard design', 'Web layouts'],
    id: 'trireg-uiux-web',
    liveUrl: 'https://www.figma.com/design/tukviOiiuBGE4KOeuECMnI/TRIREG-NEW?t=9EbKOhq0bAGZVN7q-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: 'May 2025 – October 2025',
    title: 'TriReg UI/UX Design (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Australian Rewards Club web platform UI/UX — rewards and membership flows with modern visuals.',
    features: ['Rewards platform', 'Membership flows', 'Modern visuals'],
    id: 'arc-uiux-web',
    liveUrl:
      'https://www.figma.com/design/yMTyPxE0fDEwOBf3qAqPNP/ARC-WEB?node-id=0-1&p=f&t=Ko3FbWaPHcuRAI0D-0',
    platform: 'Web',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Web UI/UX'],
    timeline: 'October 2025',
    title: 'ARC - Australian Rewards Club (Web)',
  },
  {
    categoryId: 'figma-projects',
    description: 'Mobile-first rewards app UI for Australian Rewards Club — intuitive navigation and seamless experience.',
    features: ['Mobile-first design', 'Rewards navigation', 'Seamless UX'],
    id: 'arc-uiux-mobile',
    liveUrl:
      'https://www.figma.com/design/bNtCVbo3LXVZaoCEl3RtmV/WEB-APP-VIEW-OF-AUSTRALIAN-REWARDS-CLUB?node-id=66-6&t=fpFBPiDTn72vxUEY-0',
    platform: 'Mobile',
    projectType: 'UI/UX Design',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Design Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: 'October 2025',
    title: 'Australian Rewards Club Mobile UI',
  },
  {
    categoryId: 'figma-projects',
    description: 'Plant care and community app UI — track, monitor, and care for plants with a calming, simple interface.',
    features: ['Plant tracking', 'Community features', 'Calming UI'],
    id: 'plantpal-uiux',
    liveUrl:
      'https://www.figma.com/design/7A48SiV6ks8z2NKc1BOOMO/UI-UX-PROJECt?node-id=27-6&t=mFMb4oHeInEtkZdP-0',
    platform: 'Mobile',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Mobile UI/UX'],
    timeline: '2024',
    title: 'PlantPal UI/UX Design',
  },
  {
    categoryId: 'figma-projects',
    description: 'Analytics toolkit UI for Amazon sellers — profitability, eligibility, and sales potential dashboards.',
    features: ['Data visualization', 'Seller analytics', 'Dashboard design'],
    id: 'sourcing-analysis-uiux',
    liveUrl:
      'https://www.figma.com/design/p3DY30bs9Nt9f1ZCMKK97q/Sourcing-Analysis-Simplified?node-id=0-1&p=f&t=bKcLMHFOUD0GSrRN-0',
    platform: 'Web',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Web UI/UX', 'Data Visualization'],
    timeline: '2024',
    title: 'Sourcing Analysis Simplified',
  },
  {
    categoryId: 'figma-projects',
    description: 'Plant e-commerce app UI — discover, learn about, and purchase houseplants for home and office.',
    features: ['Plant e-commerce', 'Discovery & browsing', 'Shopping flows'],
    id: 'planto-uiux',
    liveUrl: 'https://www.figma.com/design/FhdXWVWA6blrVGY4r6k4AC/Planto?node-id=0-1&p=f&t=ZXxaDVWDVcUh0o4A-0',
    platform: 'Mobile',
    projectType: 'Personal UI/UX Project',
    role: 'UI/UX Designer',
    roles: ['UI/UX Designer'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Figma', 'Mobile UI/UX', 'E-commerce'],
    timeline: '2024',
    title: 'Planto',
  },
  {
    categoryId: 'cms-projects',
    description:
      'High-converting course sales funnel for professional LED installation training — ABCDE framework, 48 video modules, testimonials, and FAQ.',
    features: ['Course funnel', '48 video modules', 'Testimonials', 'Lead capture'],
    id: 'ultimate-led-course',
    liveUrl: 'https://app.gohighlevel.com/v2/preview/D0RHH7qtq1TPIQeWRhlm?notrack=true',
    platform: 'Go High Level',
    projectType: 'CMS Project',
    role: 'CMS Builder',
    roles: ['CMS Builder', 'Front-End Developer'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['Go High Level', 'Landing Pages', 'Lead Capture'],
    timeline: '2024 – 2025',
    title: 'Ultimate LED Course',
  },
  {
    categoryId: 'cms-projects',
    description:
      'Corporate WordPress site for an IT staffing firm with 23+ years of experience — services, careers, testimonials, and contact flows.',
    features: ['Corporate services', 'Careers hub', 'Lead generation', 'Divi layouts'],
    id: 'vertere-global',
    liveUrl: 'https://vertere-gs.com/',
    platform: 'WordPress',
    projectType: 'CMS Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'CMS Builder'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['WordPress', 'Divi', 'PHP', 'HTML', 'CSS'],
    timeline: '2024 – 2025',
    title: 'Vértere Global Solutions',
  },
  {
    categoryId: 'cms-projects',
    description:
      'Recruitment agency website connecting employers and talent across the Philippines — placement, executive search, RPO, and careers hub.',
    features: ['Recruitment services', 'Industry pages', 'Careers hub', 'Testimonials'],
    id: 'a7-recruitment',
    liveUrl: 'https://a7recruitment.com/',
    platform: 'WordPress',
    projectType: 'CMS Project',
    role: 'Front-End Developer',
    roles: ['Front-End Developer', 'CMS Builder'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['WordPress', 'Elementor', 'PHP', 'HTML', 'CSS'],
    timeline: '2024 – 2025',
    title: 'A7 Recruitment',
  },
  {
    categoryId: 'video-projects',
    description:
      'Professional promotional video for Kea Babies showcasing product features and brand storytelling with motion graphics and polished editing.',
    features: ['Motion graphics', 'Product showcase', 'Brand storytelling', 'Color correction'],
    id: 'kea-babies-video',
    liveUrl: null,
    platform: 'Video',
    projectType: 'Client Project',
    role: 'Video Editor',
    roles: ['Video Editor'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['Adobe Premiere Pro', 'DaVinci Resolve', 'Motion Graphics'],
    timeline: '2024 – 2025',
    title: 'Kea Babies Product Video',
  },
  {
    categoryId: 'video-projects',
    description:
      'Long-form YouTube content for an online course promotion — engaging storytelling with seamless transitions, subtitles, and professional editing.',
    features: ['Long-form content', 'Subtitles', 'Transitions', 'Audio enhancement'],
    id: 'selling-course-video',
    liveUrl: null,
    platform: 'Video',
    projectType: 'Client Project',
    role: 'Video Editor',
    roles: ['Video Editor'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['CapCut', 'DaVinci Resolve', 'Audio Editing'],
    timeline: '2024 – 2025',
    title: 'Selling Course - YouTube Long Form',
  },
  {
    categoryId: 'video-projects',
    description:
      'Personal documentary-style video exploring health challenges with emotional storytelling, cinematic editing, and thoughtful pacing.',
    features: ['Documentary style', 'Emotional storytelling', 'Cinematic editing', 'Sound design'],
    id: 'disorder-video',
    liveUrl: null,
    platform: 'Video',
    projectType: 'Personal Project',
    role: 'Video Editor',
    roles: ['Video Editor', 'Content Creator'],
    status: 'Live',
    team: 'Solo Project',
    technologies: ['Adobe Premiere Pro', 'DaVinci Resolve', 'Color Grading'],
    timeline: '2024 – 2025',
    title: 'They Told Me I Had a Disorder',
  },
  {
    categoryId: 'video-projects',
    description:
      'Trial promotion video for Webhouse showcasing platform features with dynamic pacing, text overlays, and engaging visual storytelling.',
    features: ['Platform demo', 'Text overlays', 'Dynamic pacing', 'Visual effects'],
    id: 'webhouse-trial-video',
    liveUrl: null,
    platform: 'Video',
    projectType: 'Client Project',
    role: 'Video Editor',
    roles: ['Video Editor'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['CapCut', 'Motion Graphics', 'Audio Editing'],
    timeline: '2024 – 2025',
    title: 'Webhouse Trial',
  },
  {
    categoryId: 'video-projects',
    description:
      'High-energy beauty brand promotional video for Lashonhara featuring dynamic cuts, music synchronization, and product-focused cinematography.',
    features: ['Music sync', 'Dynamic cuts', 'Product focus', 'Brand aesthetics'],
    id: 'lashonhara-video',
    liveUrl: null,
    platform: 'Video',
    projectType: 'Client Project',
    role: 'Video Editor',
    roles: ['Video Editor'],
    status: 'Live',
    team: 'Client Project',
    technologies: ['Adobe Premiere Pro', 'CapCut', 'Color Grading'],
    timeline: '2024 – 2025',
    title: 'Lashonhara Promo',
  },
]

projectCategories.forEach((category) => {
  const items = portfolioProjects.filter((project) => project.categoryId === category.id)
  category.projects = items.map((project) => ({ id: project.id, title: project.title }))
  category.projectCount = items.length
})
